export enum TipoDocumento { DNI = 'DNI', RUC = 'RUC', CE = 'CE' }
export enum TipoVia { JIRON = 'JIRON', CALLE = 'CALLE', AVENIDA = 'AVENIDA', PROLONGACION = 'PROLONGACION', ALAMEDA = 'ALAMEDA', CARRETERA = 'CARRETERA', PASAJE = 'PASAJE' }
export enum TipoUrbanizacion { URBANIZACION = 'URBANIZACION', ASENTAMIENTO_HUMANO = 'ASENTAMIENTO_HUMANO', ASOCIACION_VIVIENDAS = 'ASOCIACION_VIVIENDAS' }
export enum TipoVivienda { CASA = 'CASA', EDIFICIO = 'EDIFICIO', CONDOMINIO = 'CONDOMINIO' }
